# Generated by Django 5.0.3 on 2024-03-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='position',
        ),
        migrations.RenameField(
            model_name='compound',
            old_name='batch_no',
            new_name='cpd_id',
        ),
    ]
