# Generated by Django 5.0.3 on 2024-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_position_rename_batch_no_compound_cpd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='is_synthesis_protocol_available',
            field=models.BooleanField(default=False),
        ),
    ]
